[project]
name = "diffusiongym"
version = "0.1.0"
description = "DiffusionGym extension with new finetuning algorithms and port to PyG"
readme = "README.md"
authors = [
    { name = "QuantumDuck", email = "40206399+BrokenDuck@users.noreply.github.com" },
]
requires-python = ">=3.13,<3.14"
dependencies = ["torch<2.13", "tqdm>=4.70.0"]

[tool.uv.sources]
torch = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "pyg"
url = "https://data.pyg.org/whl/torch-2.12.0+cu130.html"
format = "flat"
explicit = true

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pytest>=9.1.1"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
files = ["diffusiongym"]
strict = true
pretty = true
