"""Diffusion Gym package."""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("diffusiongym")
except PackageNotFoundError:
    __version__ = "0.0.0"

from diffusiongym.base_models import BaseModel
from diffusiongym.core import (
    AffineFlowMarginalPreservingSDE,
    AffineGaussianForwardProcess,
    AffineSchedule,
    BaseSampler,
    ConstantDiffusionSchedule,
    DataCodec,
    DefaultEulerGaussianKernelFactory,
    DifferentiableTerminalCost,
    DynamicsCoefficients,
    EulerGaussianKernelFactory,
    EulerMaruyamaSampler,
    EulerODESampler,
    FlowDynamics,
    FlowEnvironment,
    FlowModel,
    ForwardBatch,
    GaussianMarkovKernel,
    IdentityCodec,
    LatentGeometry,
    MarkovKernel,
    MemorylessDiffusionSchedule,
    MemorylessFlowSDE,
    PolicyBundle,
    PredictionConverter,
    PredictionKind,
    ProbabilityFlowODE,
    RectifiedFlowSchedule,
    RewardBatch,
    RewardEvaluator,
    Rollout,
    RolloutRequest,
    RolloutStep,
    RolloutStorage,
    ScalarDiffusionSchedule,
    SMCSampler,
    SMCStats,
    TensorGeometry,
    TemporalScoreRescaling,
    TorchBaseSampler,
    TorchFlowModelAdapter,
    VelocityRegression,
    local_proposals,
    sinkhorn_cost,
    sinkhorn_divergence_potential,
    sinkhorn_potentials,
    tail_time_grid,
)
from diffusiongym.make import FineTuningSetup, make, make_time_grid
from diffusiongym.registry import (
    ModalityProvider,
    Registry,
    RewardProvider,
    algorithm_registry,
    base_model_registry,
    modality_registry,
    reward_provider_registry,
    reward_registry,
)
from diffusiongym.types import DDBatch, DDTensor

__all__ = [
    # core
    "AffineFlowMarginalPreservingSDE",
    "AffineGaussianForwardProcess",
    "AffineSchedule",
    # base
    "BaseModel",
    "BaseSampler",
    "ConstantDiffusionSchedule",
    # schedulers (legacy)
    "ConstantNoiseSchedule",
    "CosineScheduler",
    # types
    "DDBatch",
    "DDTensor",
    "DataCodec",
    "DefaultEulerGaussianKernelFactory",
    "DifferentiableTerminalCost",
    "DiffusionScheduler",
    # rewards
    "DummyReward",
    "DynamicsCoefficients",
    "EulerGaussianKernelFactory",
    "EulerMaruyamaSampler",
    "EulerODESampler",
    "FlowDynamics",
    "FlowEnvironment",
    "FlowModel",
    "ForwardBatch",
    "GaussianMarkovKernel",
    "IdentityCodec",
    "LatentGeometry",
    "MarkovKernel",
    "MemorylessDiffusionSchedule",
    "MemorylessFlowSDE",
    "MemorylessNoiseSchedule",
    "NoiseSchedule",
    "OptimalTransportScheduler",
    "PolicyBundle",
    "PredictionConverter",
    "PredictionKind",
    "ProbabilityFlowODE",
    "RectifiedFlowSchedule",
    "Reward",
    "RewardBatch",
    "RewardEvaluator",
    "Rollout",
    "RolloutRequest",
    "RolloutStep",
    "RolloutStorage",
    "SMCSampler",
    "SMCStats",
    "ScalarDiffusionSchedule",
    "Scheduler",
    "TensorGeometry",
    "TorchBaseSampler",
    "TorchFlowModelAdapter",
    "VelocityRegression",
    # assembly
    "FineTuningSetup",
    "ModalityProvider",
    "Registry",
    "RewardProvider",
    "algorithm_registry",
    "make",
    "make_time_grid",
    "modality_registry",
    "reward_provider_registry",
    "TemporalScoreRescaling",
    "local_proposals",
    "sinkhorn_cost",
    "sinkhorn_divergence_potential",
    "sinkhorn_potentials",
    "tail_time_grid",
    # registry (legacy)
    "base_model_registry",
    "reward_registry",
]
